<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.16</version>
	</parent>
	<groupId>com.ups.api</groupId>
	<artifactId>shipping</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>shipping</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>21</java.version>
		<swagger-annotations-version>1.5.22</swagger-annotations-version>
		<jackson-databind-nullable-version>0.2.11</jackson-databind-nullable-version>
		<jsr305.version>3.0.2</jsr305.version>

		<code-gen-oauth-execution-name>OAuth</code-gen-oauth-execution-name>
		<code-gen-oauth-spec>OAuthClientCredentials.json</code-gen-oauth-spec>
		<code-gen-appl-execution-name>shipping</code-gen-appl-execution-name>
		<code-gen-appl-spec>Shipment.json</code-gen-appl-spec>
		<main-class-name>com.ups.api.ShippingApplication</main-class-name>
	</properties>

	<dependencies>
		<!-- OPENAPI code generation dependencies -->
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>${swagger-annotations-version}</version>
		</dependency>

		<!-- @Nullable annotation -->
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>${jsr305.version}</version>
		</dependency>


		<!-- JSON processing: jackson -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson-databind-nullable-version}</version>
		</dependency>
		<!-- application dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-websocket</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-webmvc</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-websocket</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-webmvc</artifactId>
				</exclusion>
			</exclusions>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>7.25.0</version>
				<executions>
					<execution>
						<id>${code-gen-oauth-execution-name}</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/${code-gen-oauth-spec}
							</inputSpec>
							<generatorName>java</generatorName>
							<library>resttemplate</library>
							<apiPackage>org.openapitools.oauth.client.api</apiPackage>
							<modelPackage>org.openapitools.oauth.client.model</modelPackage>
							<configOptions>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>${code-gen-appl-execution-name}</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/${code-gen-appl-spec}</inputSpec>
							<generatorName>java</generatorName>
							<library>resttemplate</library>
							<apiPackage>org.openapitools.shipping.client.api</apiPackage>
							<modelPackage>org.openapitools.shipping.client.model</modelPackage>
							<configOptions>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>${main-class-name}</mainClass>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
